baseURL = "https://phatcvo.github.io"
languageCode = "en-us"
theme = "aafu"
publishDir = "public"

[build]
  writeStats = true
[permalinks]
    post = "/:year/:month/:day/:title/"
    
[params]
    title = "Phat C. Vo"
    author = "Phat C. Vo"
    description = "Website title"
    copyright = "&copy; 2025 &middot; phatcvo"
    paginate = 100

    num_posts = 100

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="logo.png">
        <link rel="icon" type="image" sizes="32x32" href="favicon.ico">
        <link rel="icon" type="image" sizes="16x16" href="favicon.ico">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Phat C. Vo"
        tagline = ""
        location = "work hard, get smart"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/phatcvo/"
            title = "LinkedIn"		
        #[[params.social.list]]
        #    icon = "fab fa-stack-overflow"
        #    url = "https://www.webofscience.com/wos/author/record/AAJ-2598-2021"
        #    title = "StackOverflow"
        #[[params.social.list]]
        #    icon = "fab fa-researchgate"
        #    url = "https://www.researchgate.net/profile/Cong-Phat-Vo?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiX2RpcmVjdCJ9fQ"
        #    title = "ResearchGate"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/vophat0607"
            title = "Twitter"
        #[[params.social.list]]
        #    icon = "fab fa-orcid"
        #    url = "https://orcid.org/0000-0001-6703-5759"
        #    title = "Orcid"
        #[[params.social.list]]
        #    icon = "ai ai-google-scholar"
        #    url = "https://scholar.google.com/citations?user=VMidGa4AAAAJ&hl=en"
        #    title = "Google Scholar"
        #[[params.social.list]]
        #    icon = "fab fa-github"
        #    url = "https://github.com/phatcvo"
        #    title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-instagram"
            url = "https://www.instagram.com/phatcvo/"
            title = "Instagram"
        [[params.social.list]]
            icon = "fab fa-youtube"
            url = "https://www.youtube.com/@phatcvo"
            title = "Youtube"
            
        

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = false   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    #[[params.showInAccordion]]
    #    item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "My research topic of interest during my PhD includes Robust Control, Human-robot interaction, Optimization, Model Predictive Control and Reinforcement Learning in Robotics. Throughout the past years, I have worked on multiple research projects surrounding the topic of Designing Integrated Strategies for Modularized Robotics/Mobility Systems including self-driving vehicle in Uncertain Environments. My current work focuses on Motion Planning, Behavior Planning, Fleet Management in Autonomous Mobility (Delivery/Patrol Robot, AMR, AGV, AV, ...)"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Senior Motion Planning Engineer"
            dates = "Dec. 2023 - *Present*"
            company = "Autonomous Robot 24Hours 7Days (AR247)"
            url = "https://ar247.co.kr/"
            details = "Specializing in developing cutting-edge motion planning algorithms for Delivery/Security Patrol Robots, Autonomous Mobile Robots (AMR), and Self-driving Vehicles that revolutionize delivery, logistics, and warehouse operations. Expertise includes designing and implementing optimized trajectory planning strategies that ensure safe and efficient navigation. This work integrates 1) Advanced Behavior Planning: Designing algorithms for intelligent decision-making in complex environments. 2) Obstacle Avoidance: Developing robust solutions for static and dynamic obstacle detection and navigation. 3) Diverse Robot Platforms: From lightweight delivery robots to heavy-duty robots with steering-style mechanisms, tailored for industrial applications. In addition, as scalability 4) Fleet Management Systems: Optimizing multi-robot coordination and task allocation for seamless operations."
        [[params.experience.list]]
            position = "Postdoctoral Researcher"
            dates = "Agu. 2021 - *Dec. 2023*"
            company = "Ulsan National Institute of Science and Technology (UNIST)"
            url = "https://rml-unist.notion.site/"
            details = "Research in Motion Planning for Autonomous systems by Predictive Optimal control, Robust-Adaptive MPC and Reinforcement Learning carrying out maximized safety and efficiency under uncertain and time-varying environments. Propose a new planning algorithm based on the merits of sampling-based and optimization-based methods."
        [[params.experience.list]]
            position = "Postdoctoral Researcher"
            dates = "Mar. 2021 – Jul. 2021"
            url = "#"
            details = "Focused on prioritized transparency in human‑robot interaction for safe collaborative tasks during teleoperation based on optimal control strategies and Improved Reinforcement Learning."
            company = "University of Ulsan (UOU)"
        [[params.experience.list]]
            position = "Graduate Researcher"
            dates = "Sept. 2017 – Feb. 2021"
            url = "#"
            details = "Handled the time‑delay and data‑packet dropout issues utilizing a predictive control algorithm delivering to effectively address challenges within Network Control Systems. Enhanced the precision of control trajectory and force tracking in robotics by introducing a novel time‑varying adaptive optimal estimator. Additionally, developed renewable and sustainable energy system control projects (Fluid‑based Triboelectric Nanogenerator; Floating Offshore Wind Turbines) to optimize as well as maximize power captured."
            company = "University of Ulsan (UOU)"
        [[params.experience.list]]
            position = "Lecturer"
            dates = "Sept. 2015 – Jul. 2017"
            url = "#"
            details = "Lecture courses: Microprocessor Programming, Basic C/C++ Programming, Circuit Design, Power Electronics, Advanced control theory"
            company = "Thu Duc College of Technology (TDC)"
        [[params.experience.list]]
            position = "Graduate Researcher and Teaching Assistant"
            dates = "Sept. 2014 – Jul. 2016"
            url = "#"
            details = "Designed and developed: Path-Tracking Control and SLAM Algorithm of Reception Robot"
            company = "Ho Chi Minh City University of Technology and Education (UTE)"
        [[params.experience.list]]
            position = "Technical Engineer"
            dates = "Sept. 2012 – Agu. 2014"
            url = "#"
            details = "Took primary responsibility for the electrical tasks of the projects (built up control box and main control program), deployed as Auto Parking Car Systems at Bitexco Financial Tower, Lim Tower, HCMC Supreme People’s Court, etc. and Industrial Production Line in CSB Energy Technology Co., Ltd., GS Battery Vietnam Co., Ltd., Hyosung Viet Nam Co., Ltd."
            company = "Automation 5S."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Mechanical and Automotive Engineering (Minor: Robotics)"
            college = "University of Ulsan"
            dates = "Sept. 2017 - Feb. 2021"
            thesis_title = "A Sensorless Reflecting Control for Bilateral Haptic Teleoperation System based on Pneumatic Artificial Muscle Actuators."
            thesis_url = "https://docs.google.com/presentation/d/1nLnLlhYPKVGLjesrk4KOT9ENs8s9XkEa3xl5JVZ8FuU/edit?usp=sharing"
        [[params.education.list]]
            degree = "M.S. in Mechatronics Engineering"
            college = "Ho Chi Minh City University of Technology and Education"
            dates = "Sept. 2014 - Jun. 2016"
            thesis_title = "Reception Robot: SLAM and Motion control"
            thesis_url = "https://docs.google.com/presentation/d/1wyqDIYaALouqbnQDtUPNyZ__W0eyas9pKhxigUzK4HY/edit?usp=sharing"
        [[params.education.list]]
            degree = "B.S. in Electrical and Electronic Engineering Technology"
            college = "Ho Chi Minh City University of Technology and Education"
            dates = "Sept. 2009 - Jul. 2013"
            thesis_title = "Research of a Network System using XBEE communication and its applications."
            thesis_url = "https://docs.google.com/presentation/d/1I8YbRjhpZmD74Za1VniCQu2MkVlxSDewq7OfwQ2ha94/edit?usp=sharing"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        #format = ["date", "authors", "title", "journal"]
        format = ["title"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        #types = ["Journal Articles (selected Control field)", "Conferences"]
        types = ["Details"]

        [[params.publication.list]]
            title = "Google Scholar"
            authors = ""
            date = ""
            journal = ""
            url = "https://scholar.google.com/citations?user=VMidGa4AAAAJ&hl=en"
            type = "Details"
        [[params.publication.list]]
            title = "Web of Science"
            authors = ""
            date = ""
            journal = ""
            url = "https://www.webofscience.com/wos/author/record/AAJ-2598-2021"
            type = "Details"
        [[params.publication.list]]
            title = "Research Gate"
            authors = ""
            date = ""
            journal = ""
            url = "https://www.researchgate.net/profile/Cong-Phat-Vo?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiX2RpcmVjdCJ9fQ"
            type = "Details"



        #[[params.publication.list]]
        #    title = "Efficient Motion Planning with Minimax Objectives: Synergizing Interval Prediction and Tree-Based Planning"
        #    authors = "C. P. Vo, P. Jung; T. H. Kim and J. H. Jeon"
        #    date = "2024"
        #    journal = "IEEE Access"
        #    url = "https://ieeexplore.ieee.org/abstract/document/10466533"
        #    type = "Journal Articles (selected Control field)"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"
        [[params.project.list]]
            title = "Github"
            url = "https://github.com/phatcvo/"
            description = "This includes almost all of the open-source code from my personal research projects that can be shared publicly, along with a few private projects kept for security reasons."
        #[[params.project.list]]
        #    title = "Educational Robot Platform"
        #    url = "git@github.com:phatcvo/ERP42-RML.git"
        #    description = "This project is developed by the WeGo Robotics company and build in MORAI for autonomous driving."
        #[[params.project.list]]
        #    title = "On The Way environment "
        #    url = "https://github.com/phatcvo/OTW-RML.git"
        #    description = "This environment is to demonstrate the local planning/decision-making algorithms"
        
        #[[params.project.list]]
        #    title = "Autonomous Mobile Robot"
        #    url = "#"
        #    description = "This is to optimize transport and automation in warehouses, factories, and healthcare, improving efficiency and flexibility."
        #[[params.project.list]]
        #    title = "Delivery Robot"
        #    url = "#"
        #    description = "This is autonomously transport goods, ensuring efficient and contactless deliveries in urban areas. They can patrol areas, monitor security, and provide real-time data to officers, improving safety and efficiency in public spaces."



    # Skill section
    [params.skill]
        title = "Technical Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "C/C++, Python, MATLAB, ROS, Git, Linux, Qt, Gym, Pygame, CVXOPT, Ipopt, MORAI, Carla, Gazebo, etc"
        #    skillrating = 90
        #[[params.skill.list]]
        #    skill = "Frameworks/Libraries: Gym, Pygame, CVXOPT, Ipopt, etc"
        #    skillrating = 70
        #[[params.skill.list]]
        #    skill = "Simulators/DevTools: MORAI, Carla, Gazebo, ROS, VS Code, Pycharm, Git, Github, etc"
        #    skillrating = 80

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "- Sport: Since I was very young, I have been playing soccer. It feels very exciting to score a goal."
        [[params.hobby.list]]
            hobby = "- Video Making: I love making‑video and always try to capture everything that happens around me."
        [[params.hobby.list]]
            hobby = "- Technical toys: Creating controllable things is fascinating."
        [[params.hobby.list]]
            hobby = "- Traveling: I like traveling. I explore beautiful places and experience new things."

[outputs]
  home = [ "HTML", "RSS","JSON"]
