baseURL: https://phatcvo.github.io/
languageCode: en-us
build:
  writeStats: true
params:
  title: phatcvo
  author: Phat C. Vo
  description: phatcvo
  copyright: 
  theme:
    mainTheme: null
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Phat C. Vo"
    tagline: 
    location: "work hard, get smart"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/phatcvo/"
        title: LinkedIn
      - icon: fab fa-twitter
        url: "https://twitter.com/phatcvo"
        title: Twitter
      - icon: fab fa-discord
        url: "https://discord.gg/6XF9xuD9"
        title: Discord
      - icon: fab fa-github
        url: "https://github.com/phatcvo"
        title: GitHub
      - icon: fab fa-youtube
        url: "https://www.youtube.com/@phatcvo-beelab"
        title: Youtube
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
  aboutme:
    title: About Me
    icon: fas fa-user
    description: My research topic of interest during my PhD includes Robust Control, Human-robot interaction, Optimization, Model Predictive Control and Reinforcement Learning in Robotics. Throughout the past years, I have worked on multiple research projects surrounding the topic of Designing Integrated Strategies for Modularized Robotics/Mobility Systems including self-driving vehicle in Uncertain Environments. My current work focuses on Motion Planning, Behavior Planning, Fleet Management System in Autonomous Mobility.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Senior Motion Planning Engineer
        dates: Dec. 2023 - *Present*
        url: "https://ar247.co.kr/"
        company: Motion Team · Autonomous Robot 24Hours 7Days (AR247)
        details: |1-
          - Designed motion planning strategies for heavy AMRs and validated them through high-fidelity simulations before deployment.
          - Trained and evaluated RL-based behavior policies within the simulation loop to enhance decision-making robustness.
          - Bridged simulation and real-world operation by integrating planning/control pipelines, improving safety and operational efficiency.
          - Developed fleet monitoring, mission planning, and operator dashboards for large-scale system operation.
          - Built scenario-driven frameworks to evaluate multi-robot path planning and conflict resolution.

      - position: Postdoctoral Researcher
        dates: Agu. 2021 - Dec. 2023
        url: "https://rml-unist.notion.site/"
        company: Robotics & Mobility Lab. (RML) · Ulsan National Institute of Science and Technology (UNIST)
        details: |1-
          - Researched and developed interval-prediction, RL, Deep RL and tree-based planning methods for uncertain and complex driving scenarios.
          - Built simulation environments to benchmark rule-based and RL decision-making.
          - Integrated planning/control algorithms into MORAI via ROS bridges with Hardware-in-the-loop (HIL) for smooth real-robot deployment.
          - Explored Carla simulator for testing local and behavior planning algorithms.

      - position: Graduate & Postdoctoral Researcher
        dates: Sept. 2017 – Feb. 2021
        url: "https://sites.google.com/view/kkahn/home-page"
        company: Fluid Power & Machine Intelligence Lab. (FPMI) · University of Ulsan (UOU)
        details: |1-
          - Applied model-based RL and predictive control for safe collaborative human-robot interaction.
          - Developed adaptive optimal estimators and addressed network delay/dropout issues in robotic systems.
          - Implemented and validated control and motion planning algorithms integrating simulation with HIL experiments.
          - Developed renewable and sustainable energy system control projects (Fluid‑based Triboelectric Nanogenerator; Floating Offshore Wind Turbines) to optimize as well as maximize power captured.
      
      - position: Lecturer
        dates: Sept. 2015 – Jul. 2017
        url: "https://english.tdc.edu.vn/"
        company: Electrical and Electronic Engineering Dept. (EEE) · Thu Duc College of Technology (TDC)
        details: |1-
          - Taught courses in microprocessor programming, C/C++, robotics, and control theory.

      - position: Technical Engineer & Graduate Researcher
        dates: Sept. 2012 – Jun. 2016
        url: "#"
        company: Ho Chi Minh City University of Technology and Education (UTE)
        details: |1-
          - Designed and deployed embedded control systems for automated parking and industrial production lines.
          - Researched and developed Motion Planning and Control Algorithms for an Autonomous Reception Robot.

  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Mechanical and Automotive Engineering
        college: University of Ulsan (UOU)
        dates: Sept. 2017 - Feb. 2021
        thesis_title: "A Sensorless Reflecting Control for Bilateral Haptic Teleoperation System based on Pneumatic Artificial Muscle Actuators."
        thesis_url: "https://docs.google.com/presentation/d/1nLnLlhYPKVGLjesrk4KOT9ENs8s9XkEa3xl5JVZ8FuU/edit?usp=sharing"
      - degree: M.S. in Mechatronics Engineering
        college: Ho Chi Minh City University of Technology and Education (UTE)
        dates: Sept. 2014 - Jun. 2016
        thesis_title: "Motion Planning and Control Algorithms for an Autonomous Reception Robot."
        thesis_url: "https://docs.google.com/presentation/d/1wyqDIYaALouqbnQDtUPNyZ__W0eyas9pKhxigUzK4HY/edit?usp=sharing"
      - degree: B.S. in Electrical and Electronic Engineering Technology
        college: Ho Chi Minh City University of Technology and Education (UTE)
        dates: Sept. 2009 - Jul. 2013
        thesis_title: "Design and Implementation of an XBee-Based Mobile Robot with Remote Control and Sensor Network Integration."
        thesis_url: "https://docs.google.com/presentation/d/1I8YbRjhpZmD74Za1VniCQu2MkVlxSDewq7OfwQ2ha94/edit?usp=sharing"
  publication:
    title: Publications
    icon: fas fa-book
    list:
      - site: Google Scholar
        url: "https://scholar.google.com/citations?user=VMidGa4AAAAJ&hl=en"
      - site: Web of Science
        url: "https://www.webofscience.com/wos/author/record/AAJ-2598-2021"
      - site: Research Gate
        url: "https://www.researchgate.net/profile/Cong-Phat-Vo-2"
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Fleet Autonomous Mobile Robot
        url: "#"
        image: "images/projects/FMS.gif"
        description: |1-
          These robots, equipped with steering-based locomotion mechanisms, have been deployed for security patrol tasks in public areas and construction sites, as well as for logistics operations in industrial environments. They autonomously navigate complex, shared internal roadways populated by humans and other vehicles such as trucks and forklifts. This project is also designed based on Conflict-Aware Dispatcher for deployment in large factory environments where AMRs operate on shared internal roads (indoor + outdoor). The system enables coordinated operation among robots and seamless interaction with web-based tools and human operators. It serves as the central control layer for scalable, safe, and intelligent fleet management—laying the foundation for smart factory automation.
          I was responsible for several core features, including:
          - Build and maintain a comprehensive simulation environment for testing and validating algorithms.
          - Behavioral Planning for real-time decision-making, including obstacle avoidance and speed profile planning.
          - Global Navigation, tailored to scenario requirements and factory map data.
          - Local Trajectory Generation Algorithms to ensure smooth and feasible motion control.
          - Collision Risk Assessment and Safety Validation to guarantee reliable and safe navigation.
          - Task Scheduling and Dispatching: Dynamically assigns schedules and inspection tasks to each robot based on real-time conditions and system priorities.
          - Multi-Robot Path Planning and Conflict Resolution: Manages priority-based rerouting and waiting strategies to prevent congestion and resolve conflicts in real time, especially in narrow roads and intersections shared by multiple robots.
          - Monitoring and Visualization: Collaborated with the front-end team to integrate a web-based dashboard that supports real-time, bidirectional messaging and logging database. It provides live updates on robot statuses, and task progress, enabling operators to remotely supervise the entire fleet.

      - title: Beebot
        url: ""
        source: "https://github.com/phatcvo/Beebot.git"
        description: This open-source project transforms a basic mobile robot into a fully autonomous system capable of navigating environments, avoiding obstacles, and executing tasks independently—without any human intervention. As a personal project, it was developed with the goal of building a complete autonomous robot stack from the ground up. The purpose was to create a practical platform for testing and validating various algorithms in real-world conditions. Through this project, I was able to integrate and experiment with key robotics modules in a realistic setting, accelerating development and deepening my understanding of autonomous systems beyond simulation environments.

      - title: Education Robot Platform (ERP42)
        url: ""
        image: "images/projects/ERP42.png"
        description: |1-
          I worked with the Educational Robot Platform (ERP) developed by WeGo Robotics, which was integrated into the MORAI simulation environment for autonomous driving research and development. Using this platform, I implemented and tested core motion planning components, specifically:
           - Implemented local planning and motion tracking algorithms in the MORAI simulator.
          - Integrated locally developed algorithms into the server-based simulation environment via the bridge node.
          - Developed a hybrid control framework for concurrent simulation and real robot operation, using simulation outputs to drive the physical robot.
          To support development and evaluation, I published key planning and tracking data to ROS topics, allowing for real-time visualization, logging, and further analysis. This setup provided a practical and extensible environment for experimenting with and validating autonomous driving algorithms on a compact, education-oriented platform.

      - title: On The Way Env. (OTW)
        url: "https://github.com/phatcvo/OnTheWay.git"
        image: "images/projects/OTW.gif"
        description: This is a customized simulation environment with customizable scenarios for autonomous vehicles to demonstrate the local planning/decision-making algorithms.
        
      - title: Human-Robot Teleoperation (HRT)
        url: ""
        image: "images/projects/HRT.png"
        description: |1-
          Human-Robot Teleoperation (HRT) is the focus of my Ph.D. thesis project, developed using MATLAB and supported by a series of published research works. It aims to establish a reliable and responsive teleoperation framework that balances both human control and robotic autonomy. The project addresses four key aspects:
            - Robustness: Stable performance despite uncertainties from the operator, environment, or sensors.
            - Performance: Effective task execution with speed and accuracy.
            - Perception: Enhancing the operator’s awareness of the remote environment.
            - Transparency: Accurately reflecting the environment and robot state to the operator. 
          To find further details in my thesis defense presentation available in the Education section.

      - title: Variable Stiffness Actuator (VSA) 
        url: ""
        image: "images/projects/VSA.jpg"
        link: "https://ieeexplore.ieee.org/abstract/document/8932102"
        description: |1-
          This project designs and controls a Variable Stiffness Actuator (VSA) for quadruped robot legs to enhance adaptability, shock absorption, and energy efficiency. The VSA consists of two actuators: one controls joint position, the other adjusts stiffness by modulating an elastic element. This allows real-time tuning of joint compliance independently from position.
          The control system includes:
            - A high-level controller that plans motion and desired forces,
            - A low-level controller that adjusts both position and stiffness using sensor feedback.
          By integrating VSA into each leg, the robot can achieve softer landings, better stability on uneven terrain, and improved safety when interacting with humans. This approach mimics animal-like locomotion and is ideal for dynamic and unpredictable environments.
      - title: Reception Robot
        url: ""
        image: "images/projects/Human.png"
        description: This M.S. thesis focuses on developing an autonomous service robot for indoor spaces such as lobbies, with contributions in SLAM-based map creation and tracking control for safe path following.
            
  skill:
    title: Technical Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "[Programming & Algorithms] C/C++, Python, MATLAB, Reinforcement Learning & Optimal Control. [Simulation & Development Tools] RViz (ROS), MORAI, Gazebo, Carla, MATLAB Simulink, Qt, Gym, Pygame, Git, Docker, Linux. [Middleware & Cloud]: MQTT, REST API, ROS/ROS2, Modbus, AWS."
        # skillrating: 80
      
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
